server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realtimedb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: realtime-service
