server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./data/realtimedb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: realtime-service
vendor:
  api:
    base-url: https://vendor.example/api
