server:
  port: 8080
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: realtime-service
vendor:
  api:
    base-url: https://vendor.example/api

resilience4j:
  retry:
    instances:
      vendorRetry:
        maxAttempts: 3
        waitDuration: 1s
  ratelimiter:
    instances:
      vendorRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 1m
        timeoutDuration: 2s
  circuitbreaker:
    instances:
      vendorCircuitBreaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        slidingWindowSize: 5
